In [10]:
import pandas as pd
import pickle

df1 = pd.read_csv("INMET_NE_BA_A401_SALVADOR_01-01-2024_A_31-12-2024.CSV", sep = ';', encoding = 'latin1', skiprows=8) 
df2 = pd.read_csv("INMET_NE_BA_A401_SALVADOR_01-01-2025_A_30-09-2025.CSV", sep = ';', encoding = 'latin1', skiprows=8) 

df_total = pd.concat([df1, df2], ignore_index=True)
df_total

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2024/01/01,0000 UTC,0,"1006,7","1006,7","1005,8",NaN,"26,8","22,8","26,8","26,6","22,8","22,6",79.0,78.0,79.0,66.0,"5,3","1,4",NaN
1,2024/01/01,0100 UTC,0,"1006,9","1006,9","1006,7",NaN,"26,7","22,6","26,8","26,5","22,8","22,4",79.0,77.0,78.0,62.0,"5,5","1,2",NaN
2,2024/01/01,0200 UTC,0,"1006,9","1007,1","1006,8",NaN,"26,5","22,9","26,7","26,4",23,"22,5",81.0,78.0,81.0,75.0,"4,6","1,2",NaN
3,2024/01/01,0300 UTC,0,"1006,5","1006,9","1006,5",NaN,"26,3","22,7","26,5","26,2","22,9","22,6",82.0,80.0,81.0,69.0,"4,6","1,1",NaN
4,2024/01/01,0400 UTC,0,"1006,5","1006,6","1006,5",NaN,26,"22,6","26,3","25,7","22,7","22,5",82.0,81.0,81.0,56.0,"4,2","0,8",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15331,2025/09/30,1900 UTC,0,"1011,6","1011,8","1011,6",1726,"25,9","17,7","27,3","25,9","18,2","15,9",61.0,51.0,61.0,142.0,"5,1","1,4",NaN
15332,2025/09/30,2000 UTC,0,1012,1012,"1011,6","308,9","23,9","18,5","25,9","23,9","18,8","17,5",72.0,61.0,72.0,168.0,"6,4","1,7",NaN
15333,2025/09/30,2100 UTC,0,"1012,8","1012,8",1012,19,"23,3",19,"23,9","23,3","19,4","18,1",77.0,71.0,77.0,163.0,"7,9","1,9",NaN
15334,2025/09/30,2200 UTC,0,"1013,4","1013,4","1012,8",NaN,"23,3","18,1","23,4","23,1","19,1","18,1",77.0,73.0,73.0,146.0,"5,4","1,4",NaN
15335,2025/09/30,2300 UTC,0,"1014,2","1014,2","1013,4",NaN,"23,4","19,2","23,6","23,3","19,3","17,8",77.0,71.0,77.0,165.0,"5,6","1,7",NaN

In [12]:
import pandas as pd

# Renomenar columnes brasileres → angleses
df = df_total.rename(columns={
    "Data": "date",
    "Hora UTC": "hour",
    "PRECIPITAÇÃO TOTAL, HORÁRIO (mm)": "precip"
})

# Convertir data i precip
df["date"] = pd.to_datetime(df["date"], format="%Y/%m/%d")
df["precip"] = df["precip"].astype(str).str.replace(",", ".").astype(float)

# Seleccionar només les columnes útils
df_clean = df[["date", "hour", "precip"]]

# Tallar a partir de l’1 de març de 2024
df_clean = df_clean[df_clean["date"] >= "2024-03-01"]
df_clean

            date      hour  precip
1440  2024-03-01  0000 UTC     0.0
1441  2024-03-01  0100 UTC     0.0
1442  2024-03-01  0200 UTC     0.0
1443  2024-03-01  0300 UTC     0.0
1444  2024-03-01  0400 UTC     0.0
...          ...       ...     ...
15331 2025-09-30  1900 UTC     0.0
15332 2025-09-30  2000 UTC     0.0
15333 2025-09-30  2100 UTC     0.0
15334 2025-09-30  2200 UTC     0.0
15335 2025-09-30  2300 UTC     0.0

[13896 rows x 3 columns]

In [13]:
with open("climate_data_2.pkl", "wb") as f:
    pickle.dump(df, f)